import img1 from '../assets/Images/other/PROGRAM.jpg';
import img2 from '../assets/Images/course/webdesign.jpg';
import img3 from '../assets/Images/other/computer application.jpg';
import img4 from '../assets/Images/course/digital-marketing.avif';
import img5 from '../assets/Images/course/adca1.webp';
import img6 from '../assets/Images/course/tallyprime1.jpg';
import img7  from '../assets/Images/course/dtp.jpg';
import img8 from '../assets/Images/course/python.webp';
import img9 from '../assets/Images/course/graphic-design.jpg';
import img10 from '../assets/Images/course/Ethical-Hacking.jpeg';
import sunita from '../assets/Images/other/sunita-bhatt-programming-language-trainer-fica.webp'
import ravinder from '../assets/Images/other/ravinder-bhatt-web-development-trainer.jpg';
import shivani from '../assets/Images/other/Shivani Pundir.jpg';
import sneha from '../assets/Images/other/Sneha Rana.png';

const Comcoursedata=[
    {    id:1,
        img:img1,
        title:"Programming & Language Course",
        heading:"Join Our Popular Programming Courses & Build Coding Skills",
        p1:"<strong>Programming</strong> is the foundation of modern technology where developers write structured instructions, called<strong> computer programs,</strong> to make computers perform specific tasks and solve real-world problems.",
        p2:"In the<strong> Programming Classes at FICA Institute, </strong>students learn how to communicate with computers using popular <strong>programming languages like C, C++ and Java.</strong> These languages are used to design algorithms, build logical thinking, and control how software applications function in real-time environments.",
        p3:"This course focuses on <strong>practical coding, problem-solving skills and industry-oriented programming concepts,</strong> helping students build a strong base for careers in <strong>software development, IT and computer applications.</strong>",
        fimg:sunita,
        fname:"Sunita Bhatt",
        fabout:"Programming & Language Trainer | C, C++ & Java Instructor",
        cp1:" <strong>The Programming Training Program at Federal Institute of Computer Application (FICA)</strong> is specially designed for students who want to build a <strong>strong foundation in computer programming and software development.</strong>",
        cp2:"This course focuses on <strong>logic building, problem-solving techniques and real-world coding practices</strong> using <strong>industry-relevant programming languages.</strong> Students learn how programs work internally and how to write clean, structured and efficient code.",
        cp3:"Through hands-on training in <strong>C, C++ and Java,</strong> learners gain a clear understanding of both <strong>procedural and object-oriented programming concepts.</strong> The course prepares students for <strong>higher studies, competitive exams and entry-level programming roles</strong> in the IT and software industry.",
        cp4:"This <strong>Programming & Language Course in Rishikesh</strong> is ideal for school students, college learners, beginners, and job seekers who want to enter the <strong>IT and software development field.</strong> As a trusted <strong>programming training institute in Rishikesh,</strong> FICA focuses on logic building, real coding practice, and problem-solving skills required for modern programming jobs and competitive examinations.",
        heading1:"1st Semester: C Language (Programming Foundation)",
        head1:[
            " Strong understanding of <strong>programming fundamentals & logic building.</strong>",
            " <strong>Structured programming concepts</strong> for writing clean and organized code.",
            " Low-level memory control for <strong>efficient program execution.</strong>",
            " <strong>Portable programs</strong> that work across different operating systems.",
            " Wide range of <strong>built-in data types, operators & functions.</strong>",
            " Use of <strong>standard C libraries</strong> for real-world problem solving.",
        ],
        heading2:"2nd Semester: C++ Language (Object-Oriented Programming)",
        head2:[
                " In-depth knowledge of <strong>Object-Oriented Programming (OOP)</strong> concepts.",
                "Understanding of <strong>classes, objects, inheritance & polymorphism.</strong>",
                " Efficient <strong>data structures</strong> and memory management techniques.",
                " <strong>Multi-threading support</strong> for performance-based applications.",
                " Use of <strong>templates</strong> for reusable and optimized code.",
        ],
        heading3:"3rd Semester: Java Language (Platform-Independent Programming)",
       head3:[
            " Development of <strong>platform-independent applications.</strong>",
            " Strong command over <strong>Java Object-Oriented Programming concepts.</strong>",
            " <strong>Automatic memory management</strong> and garbage collection.",
            " <strong>Multithreading</strong> for high-performance applications.",
            " Access to <strong>rich Java libraries & APIs</strong> for real-world projects.",
        ], 
        lastcontent:"Students who want to strengthen their computer fundamentals along with programming can also enroll in our ADCA Course or explore practical accounting skills through our Tally Prime Course to improve overall job readiness.",
        faq:[
            {
            question: "What is Programming & Language Course?",
            answer:"The Programming & Language Course at FICA Rishikesh teaches C, C++ and Java programming with a focus on logic building, problem solving and practical coding skills."
             },
            {
            question: "Who can join the Programming course?",
            answer:"Students, beginners, job seekers and anyone interested in learning programming and software development can join this course."
            },
            {
            question:"What is the duration of the Programming & Language Course?",
            answer:"The duration of the Programming & Language Course is 6 months with regular practical training.",
            },
            {
            question:"What career options are available after this course?",
            answer:"After completing this course, students can apply for junior programmer roles, pursue advanced programming studies or prepare for IT-related competitive exams.",
            },
            {
            question:"Is this programming course suitable for beginners?",
            answer:"Yes, the Programming & Language Course at FICA Rishikesh is beginner-friendly and starts from basic programming concepts, logic building, and step-by-step practical coding.",
            }

        ],
        cardhead:"What This Programming Course Includes",
        time:" 6 Months Programming Training",
        daytime:" 1 Hour Daily Practical Coding Classes",
        info:[
            " Hands-on Programming Practice",
            " Weekly Coding Assignments",
            " Logic Building & Problem Solving",
            " ISO-Certified Institute Course Certificate",
        ]
    },
    {    id:2,
        img: img2,
        title:"Web Designing Course",
        heading:"Professional Web Designing Course in Rishikesh",
        p1:"Learn modern website designing skills with practical training and real-world projects at FICA.",
        p2:"",
        p3:"",
        fimg:ravinder,
        fname:"Ravinder Bhatt",
        fabout:"<strong>Ravinder Bhatt</strong> is an experienced <strong>Web Designing & Front-End Development Trainer</strong> at <strong>Federal Institute of Computer Application (FICA), Rishikesh.</strong> He specializes in <strong>HTML, CSS, JavaScript, Bootstrap, Responsive Design, and WordPress,</strong> focusing on real-world projects and job-ready skills.",
        cp1:"The <strong>Web Designing Course at Federal Institute of Computer Application (FICA), Rishikesh</strong> is designed to help students master modern website designing skills using <strong>HTML5, CSS3, JavaScript, Bootstrap, and WordPress.</strong> This course focuses on creating <strong>responsive, user-friendly, and visually appealing websites</strong> that meet current industry standards.",
        cp2:"Through <strong>hands-on practical training and live projects,</strong> students learn website layout design, UI/UX basics, hosting, domain management, and website deployment. After completing this course, learners can work as <strong>Web Designers, Front-End Developers, Freelancers,</strong> or pursue advanced studies in web development.",
        cp3:"This <strong>Web Designing course in Rishikesh</strong> is ideal for students, graduates, job seekers, and freelancers who want to build a career as a <strong>Web Designer, Front-End Developer, UI Designer, or Freelance Website Developer.</strong> As a trusted <strong>web designing training institute in Rishikesh,</strong> FICA focuses on industry-ready skills including responsive layouts, performance optimization, SEO-friendly website structure, and live website deployment.",
        cp4:"",
        heading1:"",
        head1:[
            " <strong>HTML5, CSS3 & JavaScript</strong> - Core front-end technologies",
            " <strong>Responsive Web Design</strong> - Mobile & tablet friendly layouts",
            " <strong>Bootstrap Framework</strong> - Fast UI development",
            " <strong>WordPress CMS</strong> - Dynamic website creation",
            " <strong>Live Projects & Portfolio</strong> - Real-world experience",
        ],
        heading2:"",
        head2:["",],
        heading3:"",
        head3:["",],
        lastcontent:"Students who want to expand their career opportunities can also explore our Digital Marketing Course and Programming & Language Courses to gain skills in SEO, automation, and advanced web technologies.",
        faq:[
            {question:"Who can join the Web Designing Course at FICA?",
                answer:"The Web Designing Course at FICA is suitable for beginners, students, job seekers, freelancers, and anyone interested in website designing and front-end development.",
            },
            {
                question:"Is this Web Designing course practical?",
                answer:"Yes, this is a 100% practical Web Designing course that includes live projects, responsive website creation, and portfolio development.",
            },
            {
                question:"What jobs can I get after completing the Web Designing Course?",
                answer:"After completing this course, students can work as Web Designers, Front-End Developers, UI Assistants, or start freelancing and client projects.",

            },
            {
                question:"Does FICA provide certification after course completion?",
                answer:"Yes, FICA provides an ISO-certified Web Designing Course Certificate after successful completion of the training.",
            },
        ],
         cardhead:"What This Web Designing Course Includes",
        time:" 6 Months Web Designing Training",
        daytime:" 1 Hour Daily Practical Classes",
        info:[
           " HTML, CSS, JavaScript Practice",
           " Bootstrap & WordPress Projects",
           " Live Website Hosting & Deployment",
           " ISO-Certified Course Certificate",
        ]


    },
    {    id:3,
        img: img3 ,
        title:"Certificate in Computer Application-CCA",
        heading:"Popular Computer Courses to Boost Your Career",
        p1:"The CCA course at <strong>FICA Institute</strong> is designed for beginners to confidently learn core computer applications, office tools, and digital basics required for academic, professional, and personal growth.",
        p2:"",
        p3:"",
        fimg:sunita,
        fname:"Sunita Bhatt",
        fabout:"Certificate in Computer Application (CCA) Faculty | Computer Applications Trainer",
        cp1:"The Certificate in Computer Application (CCA) course at <strong>FICA Institute, Rishikesh</strong> is a beginner computer course designed to build strong practical skills. Learn computer basics, MS Office, typing, office automation, and essential digital skills through hands-on training, preparing you for academic, professional, and personal tasks.",
        cp2:"A major strength of the CCA course is its practical learning approach, where students work on real-time tasks such as document creation, spreadsheet handling, presentations, online communication, and basic system operations. With increasing demand for computer literacy in every field, the CCA certification helps students, job seekers, and beginners build a solid digital foundation for higher courses and entry-level office roles.",
        cp3:"This <strong>CCA course in Rishikesh</strong> is ideal for students preparing for <strong>government exams, office jobs, private sector roles, and computer-based work.</strong> After completing the <strong>Certificate in Computer Application at FICA,</strong> learners can work as <strong>Computer Operator, Data Entry Operator, Office Assistant, Front Desk Executive,</strong> or continue with advanced courses like ADCA for higher career growth.",
        cp4:"",
        heading1:"",
        head1:[
            "Computer Basics and Fundamental Concepts.",
            "MS Office and essential software applications.",
            "Typing skills with speed and accuracy improvement.",
            "Office automation tools and practical usage.",
            "Digital skills training for beginners.",
            "Internet browsing, email, and online communication.",
            "Operating system and application software installation,",
        ],
        heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"Students who want to upgrade their computer skills after CCA can also enroll in our ADCA Course, Hindi & English Typing Course, or Programming & Language Courses to improve job readiness for competitive exams and office work.",
        faq:[
            {
                question:"What is CCA course?",
                answer:"The Certificate in Computer Application (CCA) course at FICA Institute, Rishikesh is a beginner computer course that focuses on computer basics, MS Office, typing, office automation, and essential digital skills required for academic, professional, and personal use.",
            },
            {
                question:"What is the duration of CCA course?",
                answer:"The duration of the CCA course is 6 months with 2 hours of daily practical-based training at FICA Institute.",

            },
            {
                question:"What career opportunities are available after CCA?",
                answer:"After completing the CCA course, students can work as Computer Operator, Data Entry Operator, Office Assistant, Front Desk Executive, or use these skills for government exams and clerical jobs. It also builds a strong foundation for advanced courses like ADCA.",

            },
            {
                question:"Is CCA course offline or online?",
                answer:"The CCA course at FICA Institute, Rishikesh is conducted in offline mode with complete hands-on practical training.",
            },
            {
                question:"Is CCA course useful for government exams?",
                answer:"Yes, the CCA course is very useful for government exams where basic computer knowledge, MS Office skills, typing, and digital literacy are mandatory.",
            },
            {
                question:"Which languages are used in CCA course?",
                answer:"The CCA course is taught in both Hindi and English so that beginners can easily understand and learn computer concepts.",
            },
        ],
         cardhead:"What This CCA Course Includes",
        time:" 6 Months Comprehensive Training",
        daytime:" 2 Hours Daily Practical Classes",
        info:[
          " 100% Practical-Based Learning",
          " Weekly Assessments & Saturday Tests",
          "Regular Assignments & Project Work",
          " ISO-Certified Institute Course Certificate",
        ]
    },
    {    id:4,
        img: img4 ,
        title:"Digital Marketing Course",
        heading:"Digital Marketing Course in Rishikesh with Practical Training",
        p1:"<strong>Learn job-ready Digital Marketing skills</strong> including SEO, Social Media Marketing, Google Ads and analytics with practical classroom training.",
        p2:"",
        p3:"",
        fimg:ravinder,
        fname:"Ravinder Bhatt",
        fabout:"Digital Marketing Trainer | SEO & Online Marketing Expert",
        cp1:"<strong>The Digital Marketing course at FICA Institute</strong> is designed to help students master online marketing tools and strategies used by modern businesses.",
        cp2:"This course focuses on <strong>SEO, Social Media Marketing, Google Ads, content creation, email marketing and analytics</strong> with hands-on practical training and real campaign examples.",
        cp3:"This <strong>Digital Marketing course in Rishikesh</strong> is ideal for students, graduates, job seekers, entrepreneurs, and business owners who want to build a career as a <strong>Digital Marketing Executive, SEO Analyst, Social Media Manager, PPC Expert, or Freelance Marketer.</strong> As a trusted <strong>digital marketing training institute in Rishikesh,</strong> FICA provides hands-on training using live tools like Google Analytics, Google Ads, Search Console, and real campaign strategy for business growth.",
        cp4:"",
        heading1:"",
        head1:[
            " SEO (Search Engine Optimization) Training",
            " Social Media Marketing (Facebook, Instagram)",
            "Google Ads & PPC Campaigns",
            " Content & Email Marketing",
            " Website & Campaign Analytics",
            " Live Projects & Practical Assignments",
            " ISO-Certified Institute Course Certificate",
        ],
         heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"To strengthen your digital career, students can also enroll in our Web Designing Course and Programming & Language Courses, which help in website optimization, automation, and advanced marketing strategy development.",
        faq:[
            {
                question:"What is Digital Marketing?",
                answer:"Digital Marketing involves promoting products and services online using SEO, social media marketing, paid ads, content marketing and analytics.",

            },
            {
                question:"Is this Digital Marketing course practical?",
                answer:"Yes, this is a 100% practical Digital Marketing course with live tools, projects and real campaign training.",
            },
            {
                question:"What is the duration of this course?",
                answer:"The Digital Marketing Course duration is 6 months with daily practical classes.",
            },
            {
                question:"Who can join this Digital Marketing course?",
                answer:"Students, job seekers, entrepreneurs, freelancers and beginners can join this course.",
            },
        ],
        cardhead:"What This Digital Marketing Course Includes",
        time:" 6 Months Comprehensive Training",
        daytime:" 1 Hour Daily Practical Classes",
        info:[
            " 100% Practical-Based Learning",
            " Weekly Assessments & Saturday Tests",
            " Regular Assignments & Project Work",
            " ISO-Certified Institute Course Certificate",
        ],

    },
    {    id:5,
        img: img5 ,
        title:"Advance Diploma in Computer Application-ADCA",
        heading:"Enroll Our Popular Courses and Skill Up",
        p1:"Build a strong foundation in computer applications with our industry-oriented ADCA course at <strong>Federal Institute of Computer Application (FICA).</strong> Gain practical skills in office automation, accounting with Tally Prime, and modern computer tools to enhance your career opportunities.",
        p2:"",
        p3:"",
        fimg:sneha,
        fname:"Sneha Rana",
        fabout:"ADCA Course Faculty | Computer Applications Trainer",
        cp1:"The Advance Diploma in Computer Application (ADCA) course at <strong>FICA Institute, Rishikesh</strong> is designed to build strong practical and professional computer skills for students and job seekers. This program focuses on hands-on training in essential computer applications including <strong>MS Word, Excel, PowerPoint, Access, Outlook, Internet tools,</strong> and digital work practices.",
        cp2:"A key highlight of the ADCA course is in-depth training in <strong>Tally accounting software,</strong> enabling students to manage real-world business accounts, billing, GST basics, and financial records efficiently. With growing demand for computer and accounting professionals, ADCA certification opens career opportunities in offices, businesses, and finance-related sectors.",
        cp3:"This ADCA computer course is ideal for students after 10th or 12th, graduates, job seekers, and working professionals who want to build a stable career in office administration, accounting, and IT support roles. As one of the best ADCA training institutes in Rishikesh, FICA focuses on job-oriented skills that match real industry requirements and improve employment opportunities across India.",
        cp4:"Students can also enhance their career prospects by enrolling in our Tally Prime Course in Rishikesh or Programming & Language Courses, which complement the ADCA diploma and open more job opportunities.",
        heading1:"",
        head1:[
            "Strong foundation in basic and advanced computer concepts",
            "In-depth practical training in MS Word, Excel, PowerPoint, and Outlook",
            "Advanced spreadsheet management and professional presentation skills",
            "Database management using Microsoft Access",
            "Hindi and English typing with accuracy improvement techniques",
            "Real-time project work in Microsoft Office applications",
            "Internet usage, email handling, and online communication tools",
            "Introduction to graphic designing using Adobe Photoshop",
            "Basic Disk Operating System (DOS) commands",
            "Practical training in Tally Prime including accounting, GST, TDS, TCS, payroll, and shortcut keys",
            "Career-oriented ADCA training with industry-relevant skills",
            "ISO-Certified Institute Course Certificate",

        ],
        heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"",
        faq:[
            {
                question:"What is ADCA course?",
                answer:"ADCA (Advance Diploma in Computer Application) is a professional course at FICA Rishikesh covering MS Office, Tally Prime, accounting basics, internet tools, and office automation.",

            },
            {
                question:"What is the duration of ADCA course?",
                answer:"12 months with 2 hours daily practical classes.",
            },
            {
                question:"Career opportunities after ADCA?",
                answer:"Jobs in offices, accounting, IT support, data entry, and finance-related sectors.",
            },
            {
                question:"Is ADCA course offline or online?",
                answer:"The ADCA course at FICA Rishikesh is offered in offline mode with practical hands-on training.",
            },
            {
                question:"Which languages are used in ADCA course?",
                answer:"The course is taught in both English and Hindi.",
            },
        ],
        cardhead:"What This ADCA Course Includes",
        time:" 12 Months Comprehensive Training",
        daytime:" 2 Hours Daily Practical Classes",
        info:[
            " 100% Practical-Based Learning",
            "Weekly Assessments & Saturday Tests",
            " Regular Assignments & Project Work",
            " Diploma from an ISO-Certified Institute",
        ],

    },
    {    id:6,
        img: img6 ,
        title:"Tally Prime",
        heading:"Tally Prime Training Course in Rishikesh - Learn Accounting, GST & Inventory Management",
        p1:"<strong>Master Tally Prime</strong> and <strong>empower your career</strong> - Learn <strong>Accounting, GST, Payroll, and Inventory Management</strong> with hands-on training at <strong>FICA Rishikesh.</strong> Every keystroke shapes your <strong>professional success!</strong>",
        p2:"",
        p3:"",
        fimg:sunita,
        fname:"Sunita Bhatt",
        fabout:"<strong>Sunita Bhatt</strong> - Expert <strong>Tally Prime Trainer</strong> at <strong>FICA Rishikesh,</strong> specializing in <strong>Accounting, GST, Payroll, and Inventory Management</strong> with hands-on practical training.",
        cp1:"The <strong>Tally Prime Training Course at Federal Institute of Computer Application (FICA), Rishikesh</strong> offers a complete, hands-on learning experience for beginners, students, and professionals who want to master <strong>accounting, GST, payroll, inventory management, and financial reporting.</strong> Students gain practical skills in <strong>Tally Prime software</strong> to efficiently manage financial transactions, automate accounting tasks, and stay compliant with the latest <strong>GST regulations.</strong> Through step-by-step guidance, learners understand multi-company management, banking reconciliation, and how to customize Tally Prime for real-world business requirements.",
        cp2:"This course emphasizes <strong>job-oriented training,</strong> enabling students to confidently generate detailed financial reports, analyze business data, and implement effective accounting solutions. By combining theoretical knowledge with <strong>practical projects and real-world scenarios,</strong> FICA ensures that students develop a robust understanding of business operations, GST compliance, and financial management, making them fully <strong>prepared for careers in accounting and finance.</strong>",
        cp3:"This <strong>Tally Prime course in Rishikesh</strong> is ideal for commerce students, graduates, job seekers, business owners, and professionals who want to work as <strong>Accounts Executive, GST Assistant, Billing Executive, or Office Accountant.</strong> As a trusted <strong>Tally training institute in Rishikesh,</strong> FICA focuses on real-time accounting practice that matches current industry and GST compliance standards in India.",
        cp4:"",
        heading1:"",
        head1:[
            " <strong>Basic Introduction to Accountancy</strong> - Understand core accounting concepts and terminology.",
            " <strong>Double-Entry Accounting</strong> - Learn accurate bookkeeping for business transactions.",
            "<strong>Inventory Management</strong> - Track, manage, and optimize stock and supplies efficiently.",
            "<strong>Financial Reporting</strong> - Generate detailed reports for analysis, compliance, and decision-making.",
            "<strong>GST Compliance</strong> - Master GST rules, filing processes, and updates for seamless business compliance.",
            " <strong>Banking & Reconciliation</strong> - Reconcile accounts, manage banking entries, and ensure financial accuracy.",
            " <strong>Customization & User Settings</strong> - Tailor Tally Prime for company-specific needs and preferences.",
            "<strong>Multi-Company & Multi-Currency Support</strong> - Handle multiple businesses and currencies within Tally Prime.",
            "<strong>Security Features</strong> - Protect sensitive data and control user access efficiently.",
            "<strong> User-Friendly Interface</strong> - Navigate Tally Prime easily with an intuitive, beginner-friendly interface.",
        ],
        heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"Students looking to build a complete computer and accounting profile can also explore our ADCA Course and Programming & Language Courses to increase job opportunities in the private and government sectors.",
        faq:[
            {
                question:"Who can join the Tally Prime Course in Rishikesh?",
                answer:"The Tally Prime Course at FICA Rishikesh is suitable for beginners, commerce students, graduates, job seekers, and business owners who want to learn accounting and GST.",
            },
            {
                question:"Is Tally Prime training practical at FICA?",
                answer:"Yes, FICA provides 100% practical Tally Prime training including GST, payroll, inventory management, and real business accounting practice.",
            },
            {
                question:"Does FICA provide a Tally Prime certificate?",
                answer:"Yes, students receive an ISO-certified Tally Prime Course Certificate after successful completion of the training.",
            },
        ],
        cardhead:"What This Tally Prime Training Course Includes",
        time:"6 Months Tally Prime Training",
        daytime:" 1 Hour Daily Practical Accounting Classes",
        info:[
            " Hands-on Tally Prime Practice",
            " Weekly Accounting Assignments",
            " GST, Payroll & Inventory Practice",
            " ISO-Certified Institute Course Certificate",
        ],
    },

    {    id:7,
        img: img7 ,
        title:"Certificate in Desktop Publishing-DTP",
        heading:"Best DTP Course in Rishikesh - Practical Desktop Publishing Training",
        p1:"<strong>Build professional desktop publishing skills</strong> with our DTP course and learn creative page designing, layout structuring, image editing, and print-ready design techniques.",
        p2:"",
        p3:"",
        fimg:ravinder,
        fname:"Ravinder Bhatt",
        fabout:"DTP Course Faculty | Desktop Publishing & Graphic Design Trainer",
        cp1:"<strong>The Certificate in Desktop Publishing (DTP) course at FICA</strong> is designed for students who want to build creative and professional design skills for print and digital media.",
        cp2:"This course focuses on <strong>hands-on training in page layout, graphic designing, image editing, and office publishing tools,</strong> helping beginners turn creativity into practical, job-oriented skills.",
        cp3:"This <strong>DTP course in Rishikesh</strong> is ideal for students who want to work in <strong>print media, advertising agencies, publishing houses, newspapers, and design studios.</strong> After completing the <strong>Certificate in Desktop Publishing at FICA,</strong> students can build a career as <strong>DTP Operator, Graphic Designer, Layout Artist, Print Media Designer, or start freelancing in poster, brochure, banner, and visiting card design.</strong>",
        cp4:"",
        heading1:"",
        head1:[
            " Industry-standard DTP Software Training",
            "Design Principles & Visual Communication",
            " Page Layout & Print Design",
            " Image Editing & Photo Manipulation",
            " Text Formatting & Typography",
            " Project-Based Learning & Collaboration",
            "Real-World Print & Digital Applications",
            " ISO-Certified Institute Course Certificate",
        ],
        heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"Students who want to expand their design skills can also enroll in our Graphic Designing Course or combine DTP with Web Designing Training to work on digital and print media projects together.",
        faq:[
            {
                question:"What is DTP course?",
                answer:"The DTP (Desktop Publishing) course at FICA Institute, Rishikesh focuses on graphic designing, page layout creation, image editing, and professional publishing skills using industry-standard desktop publishing software.",

            },
            {
                question:"What is the duration of DTP course?",
                answer:"The Certificate in Desktop Publishing (DTP) course duration is 6 months with daily practical-based classes at FICA Institute.",
            },
            {
                question:"Which software is taught in DTP course?",
                answer:"The DTP course covers professional design tools such as Adobe Photoshop, CorelDRAW, PageMaker, and modern layout and print design techniques used in the publishing and advertising industry.",
            },
            {
                question:"Who can join the DTP course?",
                answer:"Beginners, students, job seekers, and creative individuals interested in graphic design, print media, and desktop publishing can join the DTP course.",
            },
            {
                question:"Can I do freelancing after completing DTP course?",
                answer:"Yes, after completing the DTP course at FICA, students can work as freelance DTP operators or graphic designers for projects like brochures, banners, posters, visiting cards, book layouts, and print media designs.",
            },
            {
                question:"What career options are available after DTP?",
                answer:"After completing the DTP course, students can work as Graphic Designer, DTP Operator, Layout Artist, Print Media Designer, or start their own freelance design services.",
            },
        ],
        cardhead:"What This DTP Course Includes",
        time:"6 Months Comprehensive Training",
        daytime:"1 Hour Daily Practical Classes",
        info:[
            "100% Practical-Based Learning",
            "Weekly Assessments & Saturday Tests",
            "Regular Assignments & Project Work",
            "ISO-Certified Institute Course Certificate",
        ],
    },
    {    id:8,
        img: img8 ,
        title:"Certificate in Python ",
        heading:"Python Training Course in Rishikesh - Learn Practical Coding at FICA",
        p1:"<strong>Python Training Course at FICA Rishikesh</strong> is specially designed for <strong>beginners, students, and job-oriented learners</strong> who want to build <strong>strong programming fundamentals.</strong> This course emphasizes <strong>100% practical Python coding, logic building, automation techniques, and industry-relevant Python applications</strong> used in <strong>software development, data handling, and IT careers.</strong> With expert guidance and hands-on practice, students gain the confidence to write <strong>real-world Python programs.</strong>",
        p2:"",
        p3:"",
        fimg:sunita,
        fname:"Sunita Bhatt",
        fabout:"<strong>Python Programming Trainer</strong> <br> Experienced faculty at <strong>Federal Institute of Computer Application (FICA),</strong> specializing in <strong>practical Python coding, logic building, and beginner-level programming training.</strong>",
        cp1:"The <strong>Python Training Course at Federal Institute of Computer Application (FICA), Rishikesh</strong> provides a complete introduction to one of the most <strong>powerful and in-demand programming languages</strong> in today’s IT industry. This course covers <strong>core Python concepts, logical thinking, and real-world problem solving,</strong> enabling students to use Python for <strong>web development, automation, data handling, and software applications.</strong>",
        cp2:"With its <strong>simple syntax, high flexibility, and vast library support,</strong> Python is widely used across industries such as <strong>IT, software development, data analysis, and artificial intelligence.</strong> Through <strong>hands-on practical training and project-based learning,</strong> students develop a <strong>future-ready programming foundation</strong> that helps them grow confidently in modern, technology-driven careers.",
        cp3:"",
        cp4:"",
        heading1:"",
        head1:[
            "<strong>Easy-to-Learn Python Syntax</strong> - Simple and readable syntax makes Python ideal for beginners.",
            "<strong>Wide Range of Applications</strong> - Use Python in web development, automation, data analysis, and software projects.",
            "<strong>Large & Supportive Community</strong> - Get help from a global developer community and rich documentation.",
            "<strong>Extensive Libraries & Frameworks</strong> - Work with powerful Python libraries to build real-world applications.",
            "<strong>Object-Oriented Programming Concepts</strong> - Learn OOP principles for structured and scalable coding.",
            "<strong>Efficient Data Handling</strong> - Manage, process, and analyze data using Python tools.",
            "<strong>Excellent for Task Automation</strong> - Automate repetitive tasks and improve productivity using Python scripts.",

        ],
        heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"Students who want to build a complete IT and computer career can also explore our ADCA Course, Programming & Language Courses, and Web Designing Course to improve job opportunities in private companies and government sectors.",
        faq:[
            {
                question:"Who can join the Python Training Course at FICA?",
                answer:"The Python Training Course at FICA Rishikesh is suitable for beginners, students, job seekers, and anyone who wants to learn programming and build a career in the IT field.",
            },
            {
                question:"Is the Python course practical or theoretical?",
                answer:"This Python course is 100% practical. Students learn real-world Python programming, logic building, automation tasks, and hands-on coding through regular practice sessions.",
            },
            {
                question:"Does FICA provide a certificate after course completion?",
                answer:"Yes, after successfully completing the Python Training Course, students receive an ISO-certified Python Course Certificate from FICA.",
            },
        ],
        cardhead:"What This Python Training Course Includes",
        time:" 6 Months Programming Training",
        daytime:" 1 Hour Daily Practical Coding Classes",
        info:[
            " Hands-on Programming Practice",
            " Weekly Coding Assignments",
            " Logic Building & Problem Solving",
            " ISO-Certified Institute Course Certificate",

        ],
    },
     {   id:9,
        img: img9 ,
        title:"Certificate in Graphic Design Course-GDC",
        heading:"Professional Graphic Designing Course in Rishikesh with Practical Training",
        p1:"<strong>Transform your creativity into professional design skills.</strong> Learn how to design impactful visuals, layouts, and creative content for print and digital platforms.",
        p2:"",
        p3:"",
        fimg:ravinder,
        fname:"<strong>Ravinder Bhatt</strong>",
        fabout:"Graphic Design & DTP Trainer | Creative Visual Design Expert",
        cp1:"<strong>The Graphic Designing & DTP course at FICA</strong> is designed to develop creative thinking and professional design skills required in today's digital and print industries.",
        cp2:"This course emphasizes <strong>visual communication, creative layout design, branding basics, image editing and print-ready design</strong> through real-world practical projects.",
        cp3:"This <strong>Graphic Designing course in Rishikesh</strong> is ideal for creative students, job seekers, and professionals who want to build a career as a <strong>Graphic Designer, DTP Operator, Visual Designer, Print Media Designer, or Freelance Graphic Artist.</strong> As a leading <strong>graphic design institute in Rishikesh,</strong> FICA focuses on practical design skills, real project work, and industry-standard tools used in advertising, media, and digital platforms.",
        cp4:"",
        heading1:"",
        head1:[
            "Professional Graphic Designing Software Training",
            "Color Theory & Design Fundamentals",
            "Creative Layout & Visual Composition",
            "Photo Editing & Digital Artwork",
            "Typography & Branding Basics",
            " Project-Based Practical Learning",
            " Print & Digital Media Design Skills",
            " ISO-Certified Institute Course Certificate",
        ],
        heading2:"",
        head2:[""],
        heading3:"",
        head3:[""],
        lastcontent:"Students interested in expanding their creative and digital skills can also explore our Web Designing Course and Digital Marketing Course, which help designers work in web, social media, and online branding projects.",
        faq:[
            {
                question:"What is Graphic Designing course?",
                answer:"The Graphic Designing course at FICA Institute, Rishikesh focuses on creative visual communication, layout designing, image editing and professional design tools used in print and digital media.",
            },
            {
                question:"What is the duration of Graphic Designing course?",
                answer:"The duration of the Graphic Designing & DTP course is 6 months with daily hands-on practical training.",
            },
            {
                question:"Which software is taught in this course?",
                answer:"Students learn Adobe Photoshop, CorelDRAW and Adobe InDesign along with layout design, typography and print media concepts.",
            },
            {
                question:"Is this course suitable for beginners?",
                answer:"Yes, this course is completely beginner-friendly and designed for students, job seekers and creative learners with no prior design experience.",
            },
            {
                question:"Can I do freelancing after completing this course?",
                answer:"Yes, after completing the course, students can start freelancing in logo design, posters, social media creatives, brochures and print design projects.",
            },
            {
                question:"What career options are available after Graphic Designing?",
                answer:"Career options include Graphic Designer, DTP Operator, Creative Assistant, Print Media Designer and Freelance Graphic Designer.",
            },
        ],
        cardhead:"What This Graphic Designing Course Includes",
        time:" 6 Months Comprehensive Training",
        daytime:"1 Hour Daily Practical Classes",
        info:[
            "100% Hands-On Creative Learning",
            " Weekly Design Practice & Reviews",
            "Real Design Projects & Assignments",
            " ISO-Certified Institute Course Certificate",
        ]
    },
    //  {   id:10  ,
    //     img: img10 ,
    //     title:"Ethical Hacking Course",
    //     heading:"Enroll Our Popular Courses and Skill Up",
    //     p1:"",
    //     p2:"",
    //     p3:"",
    //     fimg: "",
    //     fname:"",
    //     fabout:"",
    //     cp1:"",
    //     cp2:"",
    //     cp3:"",
    //     cp4:"",
    //     heading1:"",
    //     head1:[""],
    //     heading2:"",
    //     head2:[""],
    //     heading3:"",
    //     head3:[""],
    //     lastcontent:"",
    //     faq:[
    //         {question:"",
    //         answer:"",
    //         },
    //     ]
    // },
]
export default Comcoursedata;